CREATE TABLE hospital_data AS
SELECT 
h.Provider_ID, h.Hospital_Name, h.Address, h.City, h.State, h.ZIP_Code, h.County_Name,
h.Phone_Number, h.Hospital_Type, h.Hospital_Ownership,
s.Communication_Nurses_Achievement_Points, s.Communication_Nurses_Improvement_Points,
s.Communication_Nurses_Dimension_Score, s.Communication_Doctors_Achievement_Points,
s.Communication_Doctors_Improvement_Points, s.Communication_Doctors_Dimension_Score,
s.Responsiveness_of_Hospital_Staff_Achievement_Points,
s.Responsiveness_of_Hospital_Staff_Improvement_Points,
s.Responsiveness_of_Hospital_Staff_Dimension_Score,
s.Pain_Management_Achievement_Points, s.Pain_Management_Improvement_Points,
s.Pain_Management_Dimension_Score, s.Communication_about_Medicines_Achievement_Points,
s.Communication_about_Medicines_Improvement_Points,
s.Communication_about_Medicines_Dimension_Score,
s.Cleanliness_and_Quietness_of_Hospital_Environment_Achievement_Points,
s.Cleanliness_and_Quietness_of_Hospital_Environment_Improvement_Points,
s.Cleanliness_and_Quietness_of_Hospital_Environment_Dimension_Score,
s.Discharge_Information_Achievement_Points, s.Discharge_Information_Improvement_Points,
s.Discharge_Information_Dimension_Score,
s.Overall_Rating_of_Hospital_Achievement_Points,
s.Overall_Rating_of_Hospital_Improvement_Points,
s.Overall_Rating_of_Hospital_Dimension_Score 
from hospitals h, survey_responses s
where h.Provider_ID = s.Provider_ID;
